rightscale_username: 'Base64.encode64(your_username)'
rightscale_password: 'Base64.encode64(your_password)'
github_oauth: 'your github oauth'
rightscale_account_id: '44210'
api_key: 'currently not used'